<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{

    public function run()
    {
        DB::table('users')->insert([
            [
                'login' => 'Guest',
                'password' => Hash::make('1234'),
                'name' => 'Ciemins',
                'image' => 'guest.jpg',
                'surname' => 'Ciemo',
                'sex' => 2,
                'age' => 100,
                'weight' => 110,
                'bench' => null,
                'squat' => null,
                'deadlift' => null,
                'role' => 'guest',
            ],
            [
                'login' => 'admin',
                'password' => Hash::make('007admin007'),
                'name' => 'Galvenais',
                'image' => 'admin.jpg',
                'surname' => 'Kungs',
                'sex' => 1,
                'age' => 100,
                'weight' => 100,
                'bench' => null,
                'squat' => null,
                'deadlift' => null,
                'role' => 'admin',
            ],
            [
                'login' => 'Test1',
                'password' => Hash::make('1234'),
                'name' => 'Dmitrijs',
                'image' => '1.jpg',
                'surname' => 'Sunduks',
                'sex' => 1,
                'age' => 19,
                'weight' => 83,
                'bench' => 135,
                'squat' => 150,
                'deadlift' => 165,
                'role' => 'user',
            ],
            [
                'login' => 'Tes2',
                'password' => Hash::make('1234'),
                'name' => 'Vladislavs',
                'image' => '2.jpg',
                'surname' => 'Temirjovs',
                'sex' => 1,
                'age' => 23,
                'weight' => 110,
                'bench' => 145,
                'squat' => 215,
                'deadlift' => 220,
                'role' => 'user',
            ],
            [
                'login' => 'Test3',
                'password' => Hash::make('1234'),
                'name' => 'Mārcis',
                'image' => '3.jpg',
                'surname' => 'Kalniņš',
                'sex' => 1,
                'age' => 33,
                'weight' => 130,
                'bench' => 180,
                'squat' => 245,
                'deadlift' => 230,
                'role' => 'user',
            ],
            [
                'login' => 'Test13',
                'password' => Hash::make('1234'),
                'name' => 'Romāns',
                'image' => '4.jpg',
                'surname' => 'Vasiļjevs',
                'sex' => 1,
                'age' => 36,
                'weight' => 160,
                'bench' => 182.5,
                'squat' => 205,
                'deadlift' => 225,
                'role' => 'user',
            ],
            [
                'login' => 'Test4',
                'password' => Hash::make('1234'),
                'name' => 'Kirills',
                'image' => '5.jpg',
                'surname' => 'Lohmatovs',
                'sex' => 1,
                'age' => 19,
                'weight' => 65,
                'bench' => 72.5,
                'squat' => 112.5,
                'deadlift' => 130,
                'role' => 'user',
            ],
            [
                'login' => 'Test5',
                'password' => Hash::make('1234'),
                'name' => 'Genādijs',
                'image' => '6.jpg',
                'surname' => 'Smorigo',
                'sex' => 1,
                'age' => 62,
                'weight' => 90,
                'bench' => 132.5,
                'squat' => 150,
                'deadlift' => 190,
                'role' => 'user',
            ],
            [
                'login' => 'Test6',
                'password' => Hash::make('1234'),
                'name' => 'Ņikita',
                'image' => '7.jpg',
                'surname' => 'Tkačenko',
                'sex' => 1,
                'age' => 21,
                'weight' => 100,
                'bench' => 155,
                'squat' => 200,
                'deadlift' => 215,
                'role' => 'user',
            ],
            [
                'login' => 'Test7',
                'password' => Hash::make('1234'),
                'name' => 'Antons',
                'image' => '8.jpg',
                'surname' => 'Podrez',
                'sex' => 1,
                'age' => 37,
                'weight' => 80,
                'bench' => 100,
                'squat' => 105,
                'deadlift' => 140,
                'role' => 'user',
            ],
            [
                'login' => 'Test8',
                'password' => Hash::make('1234'),
                'name' => 'Ņikita',
                'image' => '9.jpg',
                'surname' => 'Polovcevs',
                'sex' => 1,
                'age' => 26,
                'weight' => 90,
                'bench' => 130,
                'squat' => null,
                'deadlift' => null,
                'role' => 'user',
            ],
            [
                'login' => 'Test9',
                'password' => Hash::make('1234'),
                'name' => 'Vitālijs',
                'image' => '10.jpg',
                'surname' => 'Grudina',
                'sex' => 1,
                'age' => 37,
                'weight' => 85,
                'bench' => 100,
                'squat' => null,
                'deadlift' => null,
                'role' => 'user',
            ],
            [
                'login' => 'Test10',
                'password' => Hash::make('1234'),
                'name' => 'Darja',
                'image' => '11.jpg',
                'surname' => 'Podrez',
                'sex' => 2,
                'age' => 16,
                'weight' => 50,
                'bench' => 35,
                'squat' => 50,
                'deadlift' => 60,
                'role' => 'user',
            ],
            [
                'login' => 'Test11',
                'password' => Hash::make('1234'),
                'name' => 'Aleksandra',
                'image' => '12.jpg',
                'surname' => 'Kašina',
                'sex' => 2,
                'age' => 21,
                'weight' => 60,
                'bench' => 35,
                'squat' => 70,
                'deadlift' => 75,
                'role' => 'user',
            ],
            [
                'login' => 'Test12',
                'password' => Hash::make('1234'),
                'name' => 'Toms',
                'image' => '13.jpg',
                'surname' => 'Bumbiers',
                'sex' => 1,
                'age' => 24,
                'weight' => 75,
                'bench' => 80,
                'squat' => 80,
                'deadlift' => 120,
                'role' => 'user',
            ],
            [
                'login' => 'Test14',
                'password' => Hash::make('1234'),
                'name' => 'Sergejs',
                'image' => '14.jpg',
                'surname' => 'Mišanins',
                'sex' => 1,
                'age' => 37,
                'weight' => 100,
                'bench' => 120,
                'squat' => null,
                'deadlift' => null,
                'role' => 'guest',
            ],
            
        ]);
    }
}
